Exception on /user/register [POST]
Traceback (most recent call last):
  File "F:\work\khd\plc-dashboard\plc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\work\khd\plc-dashboard\plc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\work\khd\plc-dashboard\plc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\work\khd\plc-dashboard\plc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "F:\work\khd\plc-dashboard\plc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\work\khd\plc-dashboard\plc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\work\khd\plc-dashboard\plc\app\views\controllers\user.py", line 83, in doregister
    selUser = models.User.query.filter_by(id=userid.id).first()
AttributeError: 'str' object has no attribute 'id'
